### ISSUE TITLE
Add different crit colours to show that your crit damage is increasing

### ISSUE THREAD

**Issue by TheRealKazuki** [ThinkInvis/RoR2-Hypercrit#4]
As the title says, it would be nice to have something to show that you've gotten a higher crit damage. I know you can see it on the damage, but it's not that clear in the early game that its working. It would be nice if normal crits where completely Yellow, and the higher crit % damage you get, the more red it turns, and at like 500% cri chance, the number is crimson red. This would help with clearity since crit sounds haven't changed, and it sounds easier to add this than sound.

**Comment by TheRealKazuki** [comment]
Because I didn't clarify, what I mean by crit colour, I mean by the crit damage numbers. That way when you hit a normal 100% crit, you have a completely yellow damage number, then the colour changes depending on the crit level.

**Comment by ThinkInvis** [comment]
This would be difficult for a similar reason to #2 -- crit chance information isn't passed to the damage number handler, only whether the attack crit at all. I might have found a way around this problem recently, but it's a little involved and I'll need to try it to be sure.

**Comment by TheRealKazuki** [comment]
Oh, damn alright, I'll be looking forward to see how you will solve this!

**Comment by ThinkInvis** [comment]
Fixed by 9d44b44fc30f8edef9ed688090bdc2a17c63f72c.
