### ISSUE TITLE
Huntress with Flurry and crit above 100% is broken

### ISSUE THREAD

**Issue by TheRealKazuki** [ThinkInvis/RoR2-Hypercrit#7]
When huntress is using flurry, and her crit reaches above 100%, her flurry does 1 dmg per arrow. 

I can replicate this with only hypercrit and StartingItemsGUI (That way I can start the game off with 200% crit), and she'll always deal 1 dmg on her flurry. Her other abilites are unaffected by this.

**Comment by Jcat4609** [comment]
You can currently work around this issue by going into the cfg and setting CompensateDamage to false.
